### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/schema-template-generator#3] opened 2019-01-24 14:05 UTC
Running `docker build . -t generator-demo:latest` gave this error
```
    Complete output from command python setup.py egg_info:

        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.freenode.net.)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-1usmc36r/cffi/
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip install -r /app/requirements.txt' returned a non-zero code: 1
```
my pip --version is:
`pip 19.0.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`
I installed the requirements.

Does this work on you machine?

**Comment by daniwelter** [comment] 2019-07-08 16:33
Cannot reproduce this issue, closing ticket

**Closed by daniwelter** 2019-07-08 16:33 UTC
